GAMES = {
    "FORTNITE": "FORTNITE",
    "FC 24": "FC24",
    "TEKKEN8": "TEKKEN8",
    "VALORANT": "VALORANT",
    "COUNTER STRIKE 2": "COUNTERSTRIKE2",
    "DOTA 2": "DOTA2",
    "OVERWATCH 2": "OVERWATCH2",
    "CALL OF DUTY: MODERN WARFARE 3": "CODM3",
    "ASSETTO CORSA": "ASSETTOCORSA",
    "UFC": "UFC",
    "ROCKET LEAGUE": "ROCKETLEAGUE",
    "CALL OF DUTY": "COD",
    "M3": "M3"
}

FORMAT = {
    "1x1": "1x1",
    "2x2": "2x2",
    "5x5": "5x5"
}